### ISSUE TITLE
Feature request: Use something other than Spray so I can use it with Akka version 2.4.?

### ISSUE THREAD

**Issue by PhilAndrew** [renesca/renesca#54]
You currently use Spray, it works with Akka 2.3.something but not 2.4.something. This prevents me from using your project. Akka http replaces Spray.

**Comment by fdietze** [comment]
This should be straight forward. The only file that needs to be ported is [RestService.scala](https://github.com/renesca/renesca/blob/master/jvm/src/main/scala/renesca/RestService.scala).

I'm busy right now, so I'd appreciate a pull request.

If you have any questions or need help, just ask.

**Comment by PhilAndrew** [comment]
I'm interested, I'll have a go.

**Comment by PhilAndrew** [comment]
Works here with latest Akka http but its a hacky mess
https://github.com/PhilAndrew/renesca_hacking

https://github.com/PhilAndrew/renesca_hacking/blob/master/src/main/scala/renesca/RestService.scala

Will push after doing cleanup later.

**Comment by fdietze** [comment]
This looks good. Thank you for hacking!

**Comment by PhilAndrew** [comment]
Created the pull request here
https://github.com/renesca/renesca/pull/55

**Comment by PhilAndrew** [comment]
I got Renesca working in OSGi using Akka HTTP and JSON4S

**Comment by PhilAndrew** [comment]
I have Renesca and Neo4jOGM working in OSGi for my project. Do you have any opinion on Neo4JOGM vs this?

**Comment by fdietze** [comment]
I never worked with neo4j-ogm, but it looks like it would be better to compare it to [renesca-magic](https://github.com/renesca/renesca-magic), since both introduce a schema over the untyped graph.

If there is anything significant you find out, please share.

I'm closing this thread, since it is resolved with https://github.com/renesca/renesca/pull/55.

The next step will be #27 (Asynchronous IO).
